from django.db import models

class Member(models.Model):
    firstname = models.CharField(max_length=50)
    middlename = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    designation = models.CharField(max_length=80)
    address = models.CharField(max_length=80)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    summary = models.CharField(max_length=50)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=50)
    position = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    location = models.CharField(max_length=20)
    startdate = models.CharField(max_length=20)
    enddate = models.CharField(max_length=20)
    jobdescription = models.CharField(max_length=50)
    school = models.CharField(max_length=40)
    degree = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    startdate1 = models.CharField(max_length=20)
    enddate1 = models.CharField(max_length=20)
    brdescription = models.CharField(max_length=50)
    projectname = models.CharField(max_length=50)
    projectlink = models.CharField(max_length=30)
    projectdescription = models.CharField(max_length=50)
    skills = models.CharField(max_length=50)
    image = models.ImageField(upload_to='pictures/')
